# Generated by Django 4.1.6 on 2023-05-17 20:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Kompiuteris", "Kompiuteris"),
                            ("Vaizdo Plokštė", "Vaizdo Plokštė"),
                            ("Motininė plokštė", "Motininė plokštė"),
                            ("Įkroviklis", "Įkroviklis"),
                            ("GPS", "GPS"),
                            ("Kita", "Kita"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("s_n", models.CharField(blank=True, max_length=100, null=True)),
                ("trouble", models.CharField(blank=True, max_length=500, null=True)),
                ("comment", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("Taip", "Taip"), ("Ne", "Ne")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        blank=True,
                        choices=[("Taip", "Taip"), ("Ne", "Ne")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Užregistruotas gedimas", "Užregistruotas gedimas"),
                            ("Taisoma", "Taisoma"),
                            ("Laukiama dalių", "Laukiama dalių"),
                            ("Pataisyta", "Pataisyta"),
                            ("Atiduota klientui", "Atiduota klientui"),
                        ],
                        default="Užregistruotas gedimas",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "scratched",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "scratched_screen",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "cracked",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "charger",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "keyboard",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "hinges",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "splashed",
                    models.CharField(blank=True, default="Ne", max_length=4, null=True),
                ),
                (
                    "created_date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("closed_date", models.DateField(blank=True, null=True)),
                (
                    "in_type",
                    models.CharField(
                        blank=True,
                        choices=[("Taip", "Taip"), ("Ne", "Ne")],
                        default="Ne",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("period", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "return_comment",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("code", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_order",
            },
        ),
    ]
