# Generated by Django 4.1.6 on 2023-04-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_order_sn_remove_order_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="trouble",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Taip", "Taip"), ("Ne", "Ne")],
                max_length=100,
                null=True,
            ),
        ),
    ]
