# Generated by Django 4.1.6 on 2023-05-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_order_hinges_order_splashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="charger",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="cracked",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="hinges",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="keyboard",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="scratched",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="scratched_screen",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="splashed",
            field=models.CharField(blank=True, default="Ne", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="trouble",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
