# Generated by Django 4.1.6 on 2023-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_remove_order_id_field_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="code",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
    ]
