# Generated by Django 4.2 on 2023-05-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_order_in_type_order_period_order_return_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="s_n",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="in_type",
            field=models.CharField(
                blank=True,
                choices=[("Taip", "Taip"), ("Ne", "Ne")],
                default="Taip",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="period",
            field=models.IntegerField(blank=True, default="0", null=True),
        ),
    ]
