# Generated by Django 4.1.6 on 2023-04-26 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="closed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="created_date",
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="device_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kompiuteris", "Kompiuteris"),
                    ("Vaizdo Plokštė", "Vaizdo Plokštė"),
                    ("Motininė plokštė", "Motininė plokštė"),
                    ("Įkroviklis", "Įkroviklis"),
                    ("GPS", "GPS"),
                    ("Kita", "Kita"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("Taip", "Taip"), ("Ne", "Ne")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sn",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kompiuteris", "Kompiuteris"),
                    ("Vaizdo Plokštė", "Vaizdo Plokštė"),
                    ("Motininė plokštė", "Motininė plokštė"),
                    ("Įkroviklis", "Įkroviklis"),
                    ("GPS", "GPS"),
                    ("Kita", "Kita"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="test",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kompiuteris", "Kompiuteris"),
                    ("Vaizdo Plokštė", "Vaizdo Plokštė"),
                    ("Motininė plokštė", "Motininė plokštė"),
                    ("Įkroviklis", "Įkroviklis"),
                    ("GPS", "GPS"),
                    ("Kita", "Kita"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
