# Generated by Django 4.1.6 on 2023-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_order_closed_date_order_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="sn",
        ),
        migrations.RemoveField(
            model_name="order",
            name="test",
        ),
    ]
