# Generated by Django 4.1.6 on 2023-04-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_order_trouble_alter_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Užregistruotas gedimas", "Užregistruotas gedimas"),
                    ("Taisoma", "Taisoma"),
                    ("Pataisyta", "Pataisyta"),
                    ("Atiduota klientui", "Atiduota klientui"),
                ],
                default="Užregistruotas gedimas",
                max_length=100,
                null=True,
            ),
        ),
    ]
