# Generated by Django 4.1.6 on 2023-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="charger",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="cracked",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="keyboard",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="scratched",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
