# Generated by Django 4.1.6 on 2023-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_order_charger_order_cracked_order_keyboard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="scratched_screen",
            field=models.CharField(
                choices=[("Taip", "Taip"), ("Ne", "Ne")], default="Ne", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="charger",
            field=models.CharField(
                choices=[("Taip", "Taip"), ("Ne", "Ne")], default="Ne", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="cracked",
            field=models.CharField(
                choices=[("Taip", "Taip"), ("Ne", "Ne")], default="Ne", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="keyboard",
            field=models.CharField(
                choices=[("Taip", "Taip"), ("Ne", "Ne")], default="Ne", max_length=4
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="scratched",
            field=models.CharField(
                choices=[("Taip", "Taip"), ("Ne", "Ne")], default="Ne", max_length=4
            ),
        ),
    ]
