# Generated by Django 4.1.6 on 2023-05-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_order_charger_alter_order_comment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AddField(
            model_name="order",
            name="id_field",
            field=models.IntegerField(
                blank=True, default=22430, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
