# Generated by Django 4.1.6 on 2023-05-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_order_id_alter_order_id_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id_field",
        ),
    ]
