# Generated by Django 4.1.6 on 2023-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_order_id_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id",
        ),
        migrations.AddField(
            model_name="order",
            name="id_field",
            field=models.IntegerField(default=22430, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
