# Generated by Django 4.1.6 on 2023-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_order_id_order_id_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="id_field",
        ),
        migrations.AddField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=22433,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
